# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0010_auto_20160406_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropmix',
            name='source_type',
            field=models.CharField(choices=[(b'NASS', b'USDA NASS'), (b'XLSX', b'Excel File')], default=b'NASS', help_text=b'Crop mix data source', max_length=4),
        ),
    ]
