# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-04 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0011_auto_20160426_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropmix',
            name='cpi_adjustment_year',
            field=models.IntegerField(help_text=b'Adjust crop prices using the consumer price index for the given year.', verbose_name=b'CPI adjustment year'),
        ),
    ]
