# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-08 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0012_auto_20160804_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropmix',
            name='crop_column_name',
            field=models.CharField(blank=True, help_text=b'The name of the column specifying which crop is being measured.', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='cropmix',
            name='excel_file',
            field=models.ForeignKey(blank=True, help_text=b'Upload an Excel spreadsheet to provide agriculture data.', null=True, on_delete=django.db.models.deletion.CASCADE, to='datafiles.DataFile'),
        ),
        migrations.AlterField(
            model_name='cropmix',
            name='sheet_name',
            field=models.CharField(blank=True, help_text=b'The name of the worksheet in the Excel file containing the crop data.', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='cropmix',
            name='source',
            field=models.CharField(blank=True, choices=[(b'CENSUS', b'Census'), (b'SURVEY', b'Survey')], default=b'CENSUS', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cropmix',
            name='unit_column_name',
            field=models.CharField(blank=True, help_text=b'The name of the column specifying the unit of measurement.', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='cropmix',
            name='year_column_name',
            field=models.CharField(blank=True, help_text=b'The name of the column specifying the year of each measurement.', max_length=80, null=True),
        ),
    ]
