# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclictargetelement',
            name='scenario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scenarios.Scenario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scenario',
            name='parameter_code',
            field=models.CharField(blank=True, default=b'00060', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='parameter_name',
            field=models.CharField(default=b'flow', max_length=20),
        ),
    ]
