# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 20:44
from __future__ import unicode_literals

from django.db import migrations

def fill_scenarios(apps, schema_editor):
    """Points flow targets elements directly at their scenarios rather than
    going through a CyclicFlowTarget.
    """
    Scenario = apps.get_model('scenarios', 'Scenario')
    CyclicTarget = apps.get_model("scenarios", "CyclicTarget")
    CyclicTargetElement = apps.get_model("scenarios", "CyclicTargetElement")
    
    for element in CyclicTargetElement.objects.all():
        target = element.target
        scenario = Scenario.objects.filter(target = target)
        if scenario:
            element.scenario = scenario[0]
            element.save()
    
class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_add_target_scenario_key'),
    ]

    operations = [
        migrations.RunPython(fill_scenarios)
    ]
