# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0003_fill_target_scenario_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cyclictargetelement',
            name='target',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='target',
        ),
        migrations.DeleteModel(
            name='CyclicTarget',
        ),
    ]
