# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 19:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0004_remove_cyclic_targets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyclictargetelement',
            name='from_day',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='cyclictargetelement',
            name='from_month',
            field=models.IntegerField(choices=[(1, b'January'), (2, b'February'), (3, b'March'), (4, b'April'), (5, b'May'), (6, b'June'), (7, b'July'), (8, b'August'), (9, b'September'), (10, b'October'), (11, b'November'), (12, b'December')]),
        ),
        migrations.AlterField(
            model_name='cyclictargetelement',
            name='to_day',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='cyclictargetelement',
            name='to_month',
            field=models.IntegerField(choices=[(1, b'January'), (2, b'February'), (3, b'March'), (4, b'April'), (5, b'May'), (6, b'June'), (7, b'July'), (8, b'August'), (9, b'September'), (10, b'October'), (11, b'November'), (12, b'December')]),
        ),
    ]
