# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 18:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0005_auto_20160406_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='drought_exceedance',
            field=models.IntegerField(default=90, help_text=b'Water volume exceedance percent value to identify drought years.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
