# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 16:17
from __future__ import unicode_literals

from django.db import migrations
import utils.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0006_scenario_drought_exceedance'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='critical_season_begin',
            field=utils.modelfields.DayOfYearField(blank=True, help_text=b'Day on which the critical season to measure starts.', null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='critical_season_end',
            field=utils.modelfields.DayOfYearField(blank=True, help_text=b'Day on which the critical season to measure ends.', null=True),
        ),
    ]
