# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-04 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0012_auto_20160804_1134'),
        ('scenarios', '0007_auto_20160428_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='crop_mix',
            field=models.ForeignKey(blank=True, help_text=b'Choose a crop mix to use as an agricultural data source for this scenario.', null=True, on_delete=django.db.models.deletion.CASCADE, to='econ.CropMix'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='critical_season_begin',
            field=utils.modelfields.DayOfYearField(blank=True, help_text=b'Day on which the critical season to measure starts (MM-DD).', null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='critical_season_end',
            field=utils.modelfields.DayOfYearField(blank=True, help_text=b'Day on which the critical season to measure ends (MM-DD).', null=True),
        ),
    ]
