# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entitlements', '0002_auto_20160428_1117'),
        ('scenarios', '0008_auto_20160804_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='instream_flow_rights',
            field=models.ForeignKey(blank=True, help_text=b'Choose a set of instream flow rights that apply to this scenario.', null=True, on_delete=django.db.models.deletion.CASCADE, to='entitlements.EntitlementSet'),
        ),
    ]
