# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import entitlements.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('priority_date', models.DateField(help_text='The priority date of the entitlement.')),
                ('effective_date', models.DateField(help_text='The date on which the entitlement becomes effective.')),
                ('term', models.IntegerField(help_text='The term of the entitlement in years.')),
                ('flow_rate', models.FloatField(help_text='The flow rate of the entitlement in CFS.')),
                ('begin', entitlements.models.DayOfYearField(help_text='Month/Day on which the entitlement begins each year.', max_length=5)),
                ('end', entitlements.models.DayOfYearField(help_text='Month/Day on which the entitlement ends each year.', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='EntitlementSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PermanenceRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('order', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('order', models.IntegerField(default=100)),
            ],
        ),
        migrations.AddField(
            model_name='entitlement',
            name='entitlement_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entitlements.EntitlementSet'),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='permanence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entitlements.PermanenceRanking'),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entitlements.SecurityRanking'),
        ),
    ]
