# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 16:17
from __future__ import unicode_literals

from django.db import migrations
import utils.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('entitlements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitlement',
            name='begin',
            field=utils.modelfields.DayOfYearField(help_text='Month/Day on which the entitlement begins each year.', verbose_name='Begin Day'),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='end',
            field=utils.modelfields.DayOfYearField(help_text='Month/Day on which the entitlement ends each year.', verbose_name='End Day'),
        ),
    ]
