# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text=b'Spatial location of data (if applicable)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text=b'Spatial location of data (if applicable)', max_digits=9, null=True),
        ),
    ]
