# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowviz', '0018_delete_scenario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='huc_scale',
            field=models.IntegerField(blank=True, choices=[(2, b'HUC-2'), (4, b'HUC-4'), (6, b'HUC-6'), (8, b'HUC-8'), (10, b'HUC-10'), (12, b'HUC-12')], null=True),
        ),
    ]
