# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowviz', '0020_add_crop_mix_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gislayer',
            name='description',
            field=models.TextField(help_text=b'Briefly describe this layer.'),
        ),
        migrations.AlterField(
            model_name='gislayer',
            name='name',
            field=models.CharField(help_text=b'Choose a name for this layer.', max_length=80),
        ),
        migrations.AlterField(
            model_name='gislayer',
            name='url',
            field=models.URLField(help_text=b'Set the URL where the layer is hosted.'),
        ),
        migrations.AlterField(
            model_name='hucregion',
            name='hucid',
            field=models.CharField(help_text=b'Choose a HUC ID for the project.', max_length=12),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text=b'Briefly describe this project.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='huc_scale',
            field=models.IntegerField(blank=True, choices=[(2, b'HUC-2'), (4, b'HUC-4'), (6, b'HUC-6'), (8, b'HUC-8'), (10, b'HUC-10'), (12, b'HUC-12')], help_text=b'Choose a HUC scale for the basin this project operates in.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text=b'Choose a name for this project.', max_length=80),
        ),
        migrations.AlterField(
            model_name='project',
            name='watershed',
            field=models.ForeignKey(help_text=b'The watershed in which this project operates.', on_delete=django.db.models.deletion.CASCADE, to='watersheds.Watershed'),
        ),
    ]
