# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowviz', '0021_auto_20160426_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_project',
            field=models.BooleanField(default=False, help_text=b'Show this project on the main project listing page.'),
        ),
    ]
